### ISSUE TITLE
Layover is kort zichtbaar wanneer de pagina wordt geladen

### ISSUE THREAD

**Issue by MicheleNL** [heleensnoeck/css-to-the-rescue-new#1]
Wanneer de pagina wordt geladen zie je heel kort eventjes de layover in beeld en vervolgens de normale layout van de pagina eroverheen ingeladen worden. Kijk even waarom dit is en los dit op. Zie ook screenshot van hoe de pagina wordt gerenderd. 
<img width="683" alt="screen shot 2016-02-12 at 16 28 15" src="https://cloud.githubusercontent.com/assets/13998672/13011156/b6293816-d1a5-11e5-8d90-d40f6bc49da5.png">

**Comment by heleensnoeck** [comment]
Transitie op target element verwijders
