### ISSUE TITLE
Intrinsic sizing opdracht niet gevonden

### ISSUE THREAD

**Issue by MicheleNL** [heleensnoeck/css-to-the-rescue-new#2]
Neem deze stof nog even door en pas deze toe

**Comment by heleensnoeck** [comment]
/_Intrinsic sizing_/
#target-inner figure {
    margin: 1em;
    max-width: -webkit-min-content;
    max-width: -moz-min-content;
    max-width: min-content;
    max-width: 100em;
    background-color: red;
}
#target-inner img {
    max-width: inherit;
}
