### ISSUE TITLE
Horizontale scrollbalk bug

### ISSUE THREAD

**Issue by MicheleNL** [heleensnoeck/css-to-the-rescue-new#4]
Je layout heeft op mijn beeldscherm een horizontale scrollbalk, probeer dit op te lossen

**Comment by heleensnoeck** [comment]
overflow-x: hidden;

**Comment by MicheleNL** [comment]
Ha! Dat is inderdaad ook een manier. Echter is dat niet echt de netste oplossing. Dit is meer symptoombestrijding. Kijk even of je het echte probleem kunt vinden en op een andere manier kunt oplossen. 

Een handigheidje hier kan zijn: alles in je pagina een outline of border geven, en kijken wat nu precies het element is dat uitsteekt (waardoor de scrollbalk ontstaat)
